### PR TITLE
pre-commit configured and executed

### LINKED ISSUE #53: Document code styling and linting if required
**Is your feature request related to a problem? Please describe.**

There's evidence in a commit message of the black autoformatter being used in the past: https://github.com/executablebooks/github-activity/commit/e8df68f923d04ff5ae87e18e1a366c0f9f92b3af but it doesn't look like it's mandatory at the moment, it's not enforced in CI and there's no pre-commit or other configuration file.

The executable books [contributing guidelines](https://github.com/executablebooks/.github/blob/f78d4adb56fdaf90db6d519bc6671a9286581f9f/CONTRIBUTING.md#coding-style) say
> Coding style is largely enforced automatically, using pre-commit hooks. For Python packages, the pre-commit should include automated code formatting via Black and code linting via flake8.

**Describe the solution you'd like**

Guidance on code formatting and linting, or a statement that it's not required

**Describe alternatives you've considered**

N/A

**Additional context**

### PR DESCRIPTION
**Pull request by consideRatio**
I copied a pre-commit config from kubespawner that is reused across the JupyterHub org to a large extent.

Closes #53 by enforcing style, not by documenting it - @manics what do you think?

## This PR includes two misc commits
- ci: accept workflow_dispatch trigger (run workflow button) (8185a32)
- docs: add config reference link to .readthedocs.yml (81226fa)

## This PR has a flake8 failure still

There was one test failure I didn't fix because I was unsure how to do so. @choldgraf perhaps you can push a commit to this pr fixing this?

```
github_activity/graphql.py:132:60: F821 undefined name 'pageInfo'
```

https://github.com/executablebooks/github-activity/blob/8180a514c8caaac4ebd3abf9236581e2ee70b7f8/github_activity/graphql.py#L131-L132

### CODE REVIEW

**Comment by choldgraf** [comment]
This looks great to me!

For the flake error, I'm not quite sure what to do about it. pageInfo only exists after the first person (and is defined after that line which is why flake is unhappy i think). Perhaps we could set pageInfo to None at first so that is exists?

**Comment by consideRatio** [comment]
Aha that sounds okay to me! 👍

**Comment by consideRatio** [comment]
@choldgraf I pushed a commit initializing the variable before the loop - flake8 is now happy

**Comment by choldgraf** [comment]
Woohoo! Thanks for professionalizing this repo.a bit 🙂

**Comment by consideRatio** [comment]
Thanks for quick followup and merge @choldgraf! :tada: :heart:

**Pull request merged**
